
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAR LPAREN OR PLUS RPAREN STAR VOID re : or\n           | re_simple  or : re OR re_simple  re_simple : re_simple re_base\n                  | re_base  re_base : star\n                | plus\n                | paren\n                | CHAR\n                | VOID  star : paren STAR\n             | CHAR STAR  plus : paren PLUS\n             | CHAR PLUS  paren : LPAREN re RPAREN '
    
_lr_action_items = {'CHAR':([0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,],[8,8,-5,-6,-7,-8,-9,-10,8,8,-4,-11,-13,-12,-14,8,-15,]),'VOID':([0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,],[9,9,-5,-6,-7,-8,-9,-10,9,9,-4,-11,-13,-12,-14,9,-15,]),'LPAREN':([0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,],[10,10,-5,-6,-7,-8,-9,-10,10,10,-4,-11,-13,-12,-14,10,-15,]),'$end':([1,2,3,4,5,6,7,8,9,12,13,14,15,16,18,19,],[0,-1,-2,-5,-6,-7,-8,-9,-10,-4,-11,-13,-12,-14,-3,-15,]),'OR':([1,2,3,4,5,6,7,8,9,12,13,14,15,16,17,18,19,],[11,-1,-2,-5,-6,-7,-8,-9,-10,-4,-11,-13,-12,-14,11,-3,-15,]),'RPAREN':([2,3,4,5,6,7,8,9,12,13,14,15,16,17,18,19,],[-1,-2,-5,-6,-7,-8,-9,-10,-4,-11,-13,-12,-14,19,-3,-15,]),'STAR':([7,8,19,],[13,15,-15,]),'PLUS':([7,8,19,],[14,16,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'re':([0,10,],[1,17,]),'or':([0,10,],[2,2,]),'re_simple':([0,10,11,],[3,3,18,]),'re_base':([0,3,10,11,18,],[4,12,4,4,12,]),'star':([0,3,10,11,18,],[5,5,5,5,5,]),'plus':([0,3,10,11,18,],[6,6,6,6,6,]),'paren':([0,3,10,11,18,],[7,7,7,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> re","S'",1,None,None,None),
  ('re -> or','re',1,'p_re','AnalisaER.py',58),
  ('re -> re_simple','re',1,'p_re','AnalisaER.py',59),
  ('or -> re OR re_simple','or',3,'p_or','AnalisaER.py',63),
  ('re_simple -> re_simple re_base','re_simple',2,'p_re_simple','AnalisaER.py',67),
  ('re_simple -> re_base','re_simple',1,'p_re_simple','AnalisaER.py',68),
  ('re_base -> star','re_base',1,'p_re_base','AnalisaER.py',72),
  ('re_base -> plus','re_base',1,'p_re_base','AnalisaER.py',73),
  ('re_base -> paren','re_base',1,'p_re_base','AnalisaER.py',74),
  ('re_base -> CHAR','re_base',1,'p_re_base','AnalisaER.py',75),
  ('re_base -> VOID','re_base',1,'p_re_base','AnalisaER.py',76),
  ('star -> paren STAR','star',2,'p_star','AnalisaER.py',80),
  ('star -> CHAR STAR','star',2,'p_star','AnalisaER.py',81),
  ('plus -> paren PLUS','plus',2,'p_plus','AnalisaER.py',85),
  ('plus -> CHAR PLUS','plus',2,'p_plus','AnalisaER.py',86),
  ('paren -> LPAREN re RPAREN','paren',3,'p_paren','AnalisaER.py',90),
]
